# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz_grafica.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

vocales = [
    'a', 'e', 'i', 'o', 'u', 
    'A', 'E', 'I', 'O', 'U',
    'á', 'é', 'í', 'ó', 'ú',
    'Á', 'É', 'Í', 'Ó', 'Ú'
]

consonantes = [
    'b', 'B', 'c', 'C', 'd', 'D', 'f', 'F', 'g', 'G',
    'h', 'H', 'j', 'J', 'k', 'K', 'l', 'L', 'm', 'M',
    'n', 'N', 'ñ', 'Ñ', 'p', 'P', 'q', 'Q', 'r', 'R',
    's', 'S', 't', 'T', 'v', 'V', 'w', 'W', 'x', 'X',
    'y', 'Y', 'z', 'Z' ]

from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_analizar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_analizar.setGeometry(QtCore.QRect(320, 320, 121, 51))
        
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_analizar.setFont(font)
        self.btn_analizar.setObjectName("btn_analizar")
        self.lb_archivo = QtWidgets.QLabel(self.centralwidget)
        self.lb_archivo.setGeometry(QtCore.QRect(450, 60, 181, 41))
        
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_archivo.setFont(font)
        self.lb_archivo.setObjectName("lb_archivo")
        self.lb_texto = QtWidgets.QLabel(self.centralwidget)
        self.lb_texto.setGeometry(QtCore.QRect(450, 140, 181, 41))
        
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_texto.setFont(font)
        self.lb_texto.setObjectName("lb_texto")
        self.lb_nlineas = QtWidgets.QLabel(self.centralwidget)
        self.lb_nlineas.setGeometry(QtCore.QRect(450, 230, 281, 41))
        
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_nlineas.setFont(font)
        self.lb_nlineas.setObjectName("lb_nlineas")
        self.lb_vocales = QtWidgets.QLabel(self.centralwidget)
        self.lb_vocales.setGeometry(QtCore.QRect(30, 420, 261, 41))
        
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_vocales.setFont(font)
        self.lb_vocales.setObjectName("lb_vocales")
        self.lb_consonantes = QtWidgets.QLabel(self.centralwidget)
        self.lb_consonantes.setGeometry(QtCore.QRect(500, 420, 261, 41))
        
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_consonantes.setFont(font)
        self.lb_consonantes.setObjectName("lb_consonantes")
        self.show_consonantes = QtWidgets.QLineEdit(self.centralwidget)
        self.show_consonantes.setGeometry(QtCore.QRect(500, 460, 261, 51))
        self.show_consonantes.setObjectName("show_consonantes")
        self.show_vocales = QtWidgets.QLineEdit(self.centralwidget)
        self.show_vocales.setGeometry(QtCore.QRect(30, 460, 261, 51))
        self.show_vocales.setObjectName("show_vocales")
        self.tx_texto = QtWidgets.QTextEdit(self.centralwidget)
        self.tx_texto.setGeometry(QtCore.QRect(90, 140, 261, 51))
        self.tx_texto.setObjectName("tx_texto")
        self.tx_lineas = QtWidgets.QTextEdit(self.centralwidget)
        self.tx_lineas.setGeometry(QtCore.QRect(90, 220, 261, 51))
        self.tx_lineas.setObjectName("tx_lineas")
        self.tx_archivo = QtWidgets.QTextEdit(self.centralwidget)
        self.tx_archivo.setGeometry(QtCore.QRect(90, 60, 261, 51))
        self.tx_archivo.setObjectName("tx_archivo")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.btn_analizar.clicked.connect(self.crear_archivo)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_analizar.setText(_translate("MainWindow", "Analizar"))
        self.lb_archivo.setText(_translate("MainWindow", "Nombre del Archivo"))
        self.lb_texto.setText(_translate("MainWindow", "Texto a escribir"))
        self.lb_nlineas.setText(_translate("MainWindow", "Número de lineas en el archivo"))
        self.lb_vocales.setText(_translate("MainWindow", "Número de Vocales"))
        self.lb_consonantes.setText(_translate("MainWindow", "Número de Consonates"))

    def analizar_archivo(self, nombre_archivo):
        contVocales = 0
        contConsonantes = 0

        with open(f"{nombre_archivo}.txt", "r", encoding="utf-8") as archivo_texto:
            contenido = archivo_texto.read()
            for i in contenido:
                if i in vocales:
                    contVocales += 1
                if i in consonantes:
                    contConsonantes += 1 
        print(contVocales)
        print(contConsonantes)
        self.show_vocales.setText(str(contVocales))
        self.show_consonantes.setText(str(contConsonantes))

    def crear_archivo(self):
        nombre_archivo = self.tx_archivo.toPlainText()
        texto = self.tx_texto.toPlainText()
        lineas = self.tx_lineas.toPlainText()

        print(nombre_archivo)
        print(texto)
        print(lineas)

        with open(f"{nombre_archivo}.txt", "w", encoding="utf-8") as archivo_texto: 
            for i in range(int(lineas)):
                archivo_texto.write(texto + "\n")  # Agregar el texto con un salto de línea
        self.analizar_archivo(nombre_archivo)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())